name: Scanner Subsystem CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-push-deploy:
    runs-on: ubuntu-latest

    env:
      DBNAME: test_db
      URI: mongodb://localhost:27017

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests
      run: |
        pytest --maxfail=1 --disable-warnings -q
        coverage run -m pytest
        coverage report

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/scanner-app:latest .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/scanner-app:latest

    - name: Deploy to DigitalOcean via SSH
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: ${{ secrets.DROPLET_USER }}
        key: ${{ secrets.DROPLET_SSH_KEY }}
        script: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/scanner-app:latest
          docker stop scanner-app || true
          docker rm scanner-app || true
          docker run -d -p 80:5000 --name scanner-app ${{ secrets.DOCKERHUB_USERNAME }}/scanner-app:latest
